#!/bin/bash
. common.sh
shopt -s extglob
rm !($gatewaydir/README.md|$gatewaydir/package.json|$gatewaydir/sample-configs)
shopt -u extglob

# echo 'cleaning app root'
# slc ctl shutdown
# rm -rf $gatewaydir/*
# rm -rf $gatewaydir/.strong-pm
# rm -rf ~/.strong-pm
# rm $plaindir/resource-server/pmctl
# rm $plaindir/resource-server/runctl
# git checkout $gatewaydir/README.md
# git checkout $gatewaydir/package.json
# git checkout $gatewaydir/sample-configs

# echo 'configuring step'
# cp -r $plaindir/resource-server $gatewaydir/resource-server
# cp -r $plaindir/client $gatewaydir/client
# cp -r $stepdir/* $gatewaydir && rm $gatewaydir/install
# ./$gatewwaydir/build-servers

# echo 'starting app'
# cd $gatewaydir/resource-server
# slc start
# slc ctl set-size 1 1
# node $gatewaydir/client
