#!/bin/bash
. common.sh
rm -rf $gatewaydir/.strong-pm
rm -rf ~/.strong-pm
slc ctl shutdown
./$gatewaydir/build-servers
cd $gatewaydir/resource-server
slc start
slc ctl set-size 1 1
node $gatewaydir/client
