#!/bin/bash
stepdir=sample-configs/step-7

echo 'cleaning app root'
slc ctl shutdown
rm -rf ./*
rm -rf ~/.strong-pm
git checkout README.md
git checkout package.json
git checkout sample-configs

echo 'configuring step'
cp -r ../notes-app-plain/client ./client
cp -r ../notes-app-plain/resource-server ./resource-server
git clone https://github.com/strongloop/strong-gateway auth-server
cp -r $stepdir/* .
./build-servers

echo 'starting app'
cd resource-server
slc start
sleep 1
slc ctl set-size 1 1
cd ../auth-server
slc start
slc ctl set-size 2 1
cd ..
node client
