#!/bin/bash
shopt -s extglob

readonly stepdir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
readonly gatewaydir=$stepdir/../..
readonly plaindir=$gatewaydir/../notes-app-plain

echo 'resetting pm'
slc ctl shutdown &> /dev/null
rm -rf ~/.strong-pm &> /dev/null
rm -rf $gatewaydir/.strong-pm &> /dev/null

echo 'cleaning app root'
rm -rf $gatewaydir/!(README.md|package.json|sample-configs)
rm $plaindir/resource-server/pmctl &> /dev/null
rm $plaindir/resource-server/runctl &> /dev/null

echo 'building step'
git clone -b 'v1.0.10' --single-branch --depth 1 https://github.com/strongloop/strong-gateway $gatewaydir/auth-server
cp -r $plaindir/resource-server $gatewaydir/resource-server
cp -r $plaindir/client $gatewaydir/client
cp -r $stepdir/!(common.sh|install) $gatewaydir
cd $gatewaydir/auth-server && npm install
cd $gatewaydir/resource-server && npm install
cd $gatewaydir/client && npm install

echo 'starting app'
cd $gatewaydir/auth-server
slc start
slc ctl set-size 1 1
cd $gatewaydir/resource-server
slc start
slc ctl set-size 2 1
node $gatewaydir/client

shopt -u extglob
